- sejongsql/module/query_analyzer/mysql/query_validator.py
- sejongsql/module/query_analyzer/uri.py
입력한 쿼리에 대하여 SELECT Query인지 판별하는 모듈 구현
- close #6 
1) SELECT로 시작하지 않을 경우 탈락
(물론 반드시 select로 시작하지 않을 수 있겠지만, 학교 수업하는데 굳이 그렇게 꼬아서 내는 친구는 충분히 컷할 여지가 있다고 판단 ㅋㅋ)
2) 실행오류 발생시 탈락
3) Explain select-type에 SELECT외에 하나라도 존재할 경우 탈락
일단 이슈에 있는대로 위와 같은 조건으로만 판별하도록 구현해둔 뒤에 추후에 좋은 방법이 있으면 추가하도록 하겠음
> [feat-6] SELECT Query Validator 구현

- sejongsql/app_main/models/problem.py
- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/pgroup.py
> [feat-15] 문제집 API 구현

- sejongsql/app_main/views/users.py
- sejongsql/module/exceptions.py
- sejongsql/module/rules.py
- sejongsql/module/validator.py
- 벨리데이터 커스텀 완료!
- close #25 
1. 단일 벨리데이션 오브젝트
2. 리스트 형 벨리데이션 오브젝트 (여러개의 벨리데이션)
사용 가능합니다 :)
검증 오류 일 때, 어떠한 파람이 잘못되었는지도 잘 반환 되는거 확인했습니다.
> [feat-18] Validator 구현

- sejongsql/module/query_analyzer/mysql/query_parser.py
2019 노승민 교수님 출처인, .sql 파일 7개 (약 7500개 데이터) 를 대상으로 테스트 진행 완료. (현재는 전부 무사 통과 !)
추가적으로 다양한 .sql 파일을 받아와서 더 테스트 해볼 예정인데, 현재 env API 구현중이라 우선 임시적으로 PR날립니다.
(혹시 추가적인 피드백 있으면 부탁드립니다.)
- close #26 
본 파서는 파일 내부에, 다음과 같은 사전 조건 체킹 구문들은 다 무시함.
```
DROP DATABASE IF EXISTS  madang;
DROP USER IF EXISTS  madang@localhost;
create user madang@localhost identified WITH mysql_native_password  by 'madang';
create database madang;
grant all privileges on madang.* to madang@localhost with grant option;
commit;
USE madang;
```
해당 파서는 다음과 같이, 오직 CREATE TABLE / CREATE INDEX / INSERT 구문만 판단.
```
// 옳바른 예시 예시
CREATE TABLE userTbl
( userID CHAR(8) NOT NULL PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
addr CHAR(2) NOT NULL,
mobile1 CHAR(3),
mobile2 CHAR(8),
height SMALLINT,
mDate DATE,
INDEX …
```
> [feat-26] .sql 파서 구현

- sejongsql/module/query_analyzer/mysql/query_parser.py
- 테이블 반환 방식 변경 (딕셔너리 -> 리스트)
- join해서 주는 완성된 쿼리 집합 반환 제거
- close #29
> [feat-29] Query Parser 테이블 반환 방식 변경

- sejongsql/module/query_analyzer/mysql/query_parser.py
> [feat-31] Query Parser 버그 수정

- sejongsql/app_main/models/user.py
- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/envs.py
- sejongsql/app_main/views/users.py
세종대 서버의 문제로 인한 인증 실패를 우선,
```
if not sejong_auth.success:
return UNAUTHORIZED("Sejong University Server Error.")
```
이렇게 해놨는데, 잘 사용한게 맞을까요?
- close #33
> [feat-33] Sejong Auth API 구현

- sejongsql/module/query_analyzer/mysql/query_parser.py
> [feat-41] SQL Query Parser 테이블명 반환 수정

- sejongsql/app_main/views/pgroup.py
> [feat-49] 문제집 생성 API 수정

- .gitignore
- sejongsql/app_main/admin.py
- sejongsql/app_main/models/__init__.py
- sejongsql/app_main/models/env.py
- sejongsql/app_main/models/problem.py
- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/problems.py
- sejongsql/config/settings/production.py
> [feat-16] 문제 생성,수정,삭제,반환 API 구현

- Dockerfile
- requirements.txt
- sejongsql/config/settings/base.py
> [refac-46] 도커 컴포즈 구조 수정

- sejongsql/app_main/urls.py
- sejongsql/app_main/views/error_sample.py
* feat: 비동기 예제 추가
* feat: 비동기 예제 추가
> [develop] Ver 0.2.2

- sejongsql/module/environ.py
> [feat-60] SQL File 저장 경로 수정

- sejongsql/app_main/urls.py
- sejongsql/app_main/views/async_sample.py
- sejongsql/app_main/views/management.py
- sejongsql/module/async_queue/async_queue.py
> [feat-63] 워커 이슈 트래거 API 구현

- sejongsql/app_main/models/user.py
- sejongsql/app_main/views/users.py
- 학과 정보 추가
- close #70 
[교수님 아이디도 될란지 모르겠네]
> [feat-70] 세종대학교 구성원 인증 API 수정

- sejongsql/app_main/views/envs.py
- sejongsql/app_main/views/problems.py
- sejongsql/module/environ.py
1. Env 생성 시 넘겨주는 param에서 django 객체 제외
2. 문제 실행 api 수정
> [feat-80] Env 생성 parameter 변경

- sejongsql/app_main/views/classes.py
1. 검색된 유저 없을 때 빈리스트로 반환
2. 반복문 내에서 쿼리 여러 번 실행하는 부분 수정
> [feat-84] 분반 내 사용자 검색 API 수정

- sejongsql/app_main/serializer.py
- sejongsql/app_main/views/classes.py
기존 -> 교수이름 반환
수정 -> 교수 id, sejong_id, name, major 반환
> [feat-87] 분반 정보 및 목록 반환 API 수정

- sejongsql/app_main/urls.py
- sejongsql/app_main/views/classes.py
- sejongsql/app_main/views/users.py
교수 검색 API
분반 내 사용자 검색 API
-> 빈값 들어올 시 전체 사용자 반환
> [feat-76] 교수 검색, 분반 내 사용자 검색 API 수정

- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/pgroup.py
close #97 
특정 문제집 반환 API 구현
문제집 수정 API에 시간 포맷 검증 추가
> [feat-97] 특정 문제집 반환 및 수정 API

- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/problems.py
- sejongsql/module/environ.py
close #75 
코드가 많이 복잡해서 이해 안가시는 부분은 코멘트 남겨주시면 감사하겠습니다.
> [feat-75] 문제 관련 API 구현

- sejongsql/module/query_analyzer/mysql/query_validator.py
- sejongsql/module/query_analyzer/mysql/select_query_firewall/traverse.py
- 기존 SELECT startswith 방식 제거
- 경준씨 로직 적용 (에러 msg 변경됨 참고 @akshxl09 )
- traverse 함수 typehint 부분 bugfix 적용 @backgroundjun
> [Feat-101] SELECT Query Validator 업그레이드 적용

- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/problems.py
> [feat-110] 수정용 문제 반환 API 구현

- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/problems.py
* feat: 수정용 문제 반환 API 구현
* update: env 없을 때, 예외처리
> [develop] Ver 0.7.1

- sejongsql/app_main/views/envs.py
> [bugfix-105] env 분반 생성 시, 관리자 검증

- sejongsql/app_main/serializer.py
- sejongsql/app_main/urls.py
- sejongsql/app_main/views/status.py
> [feat-17] 통계 반환 API 구현

- sejongsql/app_main/serializer.py
- sejongsql/app_main/views/problems.py
- sejongsql/module/environ.py
> [feat-124] 문제 API 활성화 체크 방식 변경

- sejongsql/app_main/views/classes.py
기존 -> exclude를 이용해 교수 제외
수정 -> filter를 이용해 ta, st만 가져오도록 변경
> bugfix: 특정 분반 사용자 목록 반환 교수 제외 로직 변경

- sejongsql/app_main/views/problems.py
- sejongsql/module/environ.py
close #137 
기존 -> answer에 존재하는 테이블만 반환
수정 -> 해당 문제에 걸린 env의 모든 테이블을 반환
> [bugfix-137] env에 연결된 모든 테이블 반환

- sejongsql/module/query_analyzer/mysql/select_query_firewall/traverse.py
close #134 
* @ Operator 차단 로직 수정
> [bugfix-134] Select Query Firewall 모듈 @ Operator 차단하지 못하는 버그 수정

- sejongsql/app_main/serializer.py
- sejongsql/app_main/views/classes.py
- sejongsql/app_main/views/pgroup.py
- sejongsql/app_main/views/problems.py
close #140 
1. 사이드바에 비활성화된 주차가 반환되는 문제 해결
2. env 삭제하고 특정 문제 반환할 때 desc_table 반환문제 해결
> [bugfix-140] 비활된 주차 반환 및 env 삭제시 문제 반환

- sejongsql/app_main/views/status.py
- sejongsql/app_main/views/users.py
- sejongsql/module/rules.py
close #144 
통계 pagination
회원가입 이름에 한글 필수 rule 적용
> [feat-144] 통계 paging 및 이름 rule 적용

- sejongsql/app_main/views/classes.py
> [feat-146] race contion을 이용한 동시추가 방어

- sejongsql/app_main/views/users.py
> [feat-152] 비밀번호 수정 rule 적용

- sejongsql/app_main/views/problems.py
- sejongsql/app_main/views/users.py
- sejongsql/module/environ.py
close #158 
1. 구성원 인증 API 중복 검사
2. Time Limit일 때는 오답으로 처리
3. 문제 생성, 수정할 때 '\xa0' 문제 처리
> [feat-158] QA 적용
